# Generated by Django 3.2.9 on 2022-04-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Retailer', 'Retailer'), ('Supplier1', 'Supplier1'), ('Supplier2', 'Supplier2'), ('Supplier3', 'Supplier3')], default='Retailer', max_length=50),
        ),
    ]
