# Generated by Django 3.2.9 on 2022-04-08 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_supplier_mobile_number'),
        ('products', '0002_products_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_rfq_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium_leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.CharField(max_length=500)),
                ('request_description', models.CharField(max_length=999)),
                ('category', models.CharField(choices=[('Recent Leads', 'Recent Leads'), ('General Leads', 'General Leads'), ('Consumed Leads', 'Consumed Leads')], default='Recent Leads', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premiumbuyer', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premiumseller', to='suppliers.supplier')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
