# Generated by Django 3.2.9 on 2022-04-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_premium_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium_leads',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='primary_leads',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfq_leads',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
    ]
