# Generated by Django 3.1.4 on 2022-02-03 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('establishment_year', models.CharField(max_length=10)),
                ('ceo_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('mobile_number', models.BigIntegerField()),
                ('company_name', models.CharField(max_length=200)),
                ('establishment_year', models.CharField(max_length=10)),
                ('ceo_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=150)),
                ('pin_code', models.CharField(max_length=15)),
                ('state', models.CharField(choices=[('Province 1', 'Province 1'), ('Province 2', 'Province 2'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudur Paschim', 'Sudur Paschim')], max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=100)),
                ('building_number', models.CharField(blank=True, max_length=10, null=True)),
                ('locality', models.CharField(blank=True, max_length=30, null=True)),
                ('landmark', models.CharField(blank=True, max_length=50, null=True)),
                ('exim', models.CharField(blank=True, max_length=20, null=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('vat', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStatutory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exim', models.CharField(max_length=20)),
                ('pan', models.CharField(max_length=20)),
                ('vat', models.CharField(max_length=20)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suppliers.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('building_number', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=20, null=True)),
                ('locality', models.CharField(blank=True, max_length=30, null=True)),
                ('landmark', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suppliers.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
    ]
