# Generated by Django 3.1.4 on 2022-02-26 19:56

from django.db import migrations, models
import suppliers.models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=suppliers.models.Supplier.get_image_path),
        ),
        migrations.AddField(
            model_name='supplier',
            name='qr_code',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=suppliers.models.Supplier.get_image_path),
        ),
    ]
