# Generated by Django 3.2.9 on 2022-04-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20220226_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='city',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='street',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address1',
            field=models.CharField(default='Nepal,Nepal', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
