# Generated by Django 3.2.9 on 2022-04-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_auto_20220403_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_email',
            field=models.CharField(default='default@vistaar.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_phone',
            field=models.BigIntegerField(default='1234567890'),
            preserve_default=False,
        ),
    ]
