# Generated by Django 3.2.9 on 2022-04-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_auto_20220403_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='bio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
