# Generated by Django 3.2.9 on 2022-04-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_supplier_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='mobile_number',
        ),
    ]
