# Generated by Django 3.2.9 on 2022-04-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_remove_supplier_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='mobile_number',
            field=models.BigIntegerField(default='123456'),
            preserve_default=False,
        ),
    ]
