# Generated by Django 3.2.9 on 2022-04-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220403_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='a',
            field=models.CharField(default='asd', max_length=23),
            preserve_default=False,
        ),
    ]
