# Generated by Django 3.1.4 on 2022-02-28 06:00

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='keywords',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), default=[], max_length=400, size=None),
        ),
    ]
