# Generated by Django 3.2.9 on 2022-07-09 08:31

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='keywords',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=[], max_length=2000, size=None),
        ),
    ]
