# Generated by Django 3.2.9 on 2022-08-13 00:02

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='keywords',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), default=[], max_length=400, size=None),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='products.category'),
        ),
    ]
